language: c

compiler:  
    - gcc
    - clang

before_script:  
    

script:
 - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ../minijvm/c && cmake --build . && cmake --build . --target mini_jvm
